idf_component_register(SRCS pn_reader.c pn_reader_app.c pn_reader_input.c pn_bookmark_ui.c pn_style_ui.c pn_font_ui.c pn_epub_page.c pn_epub_image.c pn_epub_reader.c pn_epub_app.c pn_toc_ui.c INCLUDE_DIRS include REQUIRES pn_text pn_storage pn_font pn_display pn_format pn_image pn_library esp_hw_support)
