/* 上传持久确认、断块恢复与独占租约。/ Durable upload acknowledgments, interrupted chunks and exclusive leases. */
#include "pn_upload.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
typedef struct {uint8_t slots[2][1024],data[PN_UPLOAD_CHUNK+16];size_t lengths[2],size;bool exists[2],part,cut,bad_format,fail_install,installed,cut_commit;size_t cut_at;unsigned installs;} disk_t;
static pn_status_t read_slot(void *ctx,unsigned slot,uint8_t *out,size_t cap,size_t *n){disk_t *d=ctx;if(!d->exists[slot])return PN_EMPTY;if(d->lengths[slot]>cap)return PN_CORRUPT;memcpy(out,d->slots[slot],d->lengths[slot]);*n=d->lengths[slot];return PN_OK;}
static pn_status_t write_slot(void *ctx,unsigned slot,const uint8_t *in,size_t n){disk_t *d=ctx;size_t take=d->cut && d->cut_at<n?d->cut_at:n;memcpy(d->slots[slot],in,take);d->lengths[slot]=take;d->exists[slot]=true;return d->cut?PN_IO:PN_OK;}
static pn_status_t bind_port(void *ctx,pn_media_t *m,const pn_media_lease_t *l,const uint8_t *id,pn_journal_io_t *out){(void)id;assert(pn_media_validate(m,l)==PN_OK && l->access==PN_MEDIA_WRITE);*out=(pn_journal_io_t){ctx,read_slot,write_slot};return PN_OK;}
static pn_status_t size_port(void *ctx,uint64_t *out){disk_t *d=ctx;if(!d->part)return PN_EMPTY;*out=d->size;return PN_OK;}
static pn_status_t truncate_port(void *ctx,uint64_t size){disk_t *d=ctx;if(size>sizeof d->data)return PN_LIMIT;d->size=(size_t)size;d->part=true;return PN_OK;}
static pn_status_t write_port(void *ctx,uint64_t at,const uint8_t *bytes,size_t n){disk_t *d=ctx;if(at+n>sizeof d->data)return PN_LIMIT;memcpy(d->data+at,bytes,n);d->size=(size_t)at+n;return PN_OK;}
static pn_status_t read_port(void *ctx,uint64_t at,uint8_t *bytes,size_t cap,size_t *n){disk_t *d=ctx;if(!d->part || at>d->size)return PN_IO;size_t take=d->size-(size_t)at;if(take>cap)take=cap;memcpy(bytes,d->data+at,take);*n=take;return PN_OK;}
static pn_status_t validate_port(void *ctx,pn_upload_kind_t kind,const char *name){(void)kind;(void)name;return ((disk_t *)ctx)->bad_format?PN_UNSUPPORTED:PN_OK;}
static pn_status_t install_port(void *ctx,pn_upload_kind_t kind,const char *name,const pn_book_id_t *expected){(void)kind;(void)name;disk_t *d=ctx;pn_book_id_t actual;assert(pn_identity_bytes(d->data,d->size,&actual)==PN_OK && !memcmp(&actual,expected,sizeof actual));if(d->fail_install)return PN_IO;if(!d->installed){d->installs++;d->installed=true;}d->part=false;if(d->cut_commit){d->cut=true;d->cut_at=0;}return PN_OK;}
static pn_status_t remove_port(void *ctx){disk_t *d=ctx;d->part=false;d->size=0;return PN_OK;}
int main(void){
 disk_t *d=calloc(1,sizeof *d),*base=malloc(sizeof *base);assert(d && base);pn_upload_port_t port={d,bind_port,size_port,truncate_port,write_port,read_port,validate_port,install_port,remove_port,NULL,NULL,NULL};pn_pool_t pool;assert(!pn_pool_init(&pool,256*1024,NULL,NULL,NULL));pn_media_t media;pn_media_init(&media);assert(pn_media_attach(&media,123)==PN_OK);
 uint8_t *bytes=malloc(PN_UPLOAD_CHUNK+3);assert(bytes);for(size_t i=0;i<PN_UPLOAD_CHUNK+3;i++)bytes[i]=(uint8_t)(i*37+1);pn_upload_request_t request={.kind=PN_UPLOAD_BOOK,.size=PN_UPLOAD_CHUNK+3,.has_digest=true};strcpy(request.name,"测试.txt");request.id[0]=1;assert(pn_identity_bytes(bytes,PN_UPLOAD_CHUNK+3,&request.digest)==PN_OK);
 pn_upload_t upload={0},other={0};pn_media_lease_t reading;assert(pn_media_acquire(&media,PN_MEDIA_READ,&reading)==PN_OK);assert(pn_upload_begin(&upload,&pool,&media,&port,&request)==PN_BUSY && !upload.impl);assert(pn_media_release(&media,&reading)==PN_OK);
 assert(pn_upload_begin(&upload,&pool,&media,&port,&request)==PN_OK && pn_upload_begin(&other,&pool,&media,&port,&request)==PN_BUSY);pn_upload_state_t state;assert(pn_upload_state(&upload,&state)==PN_OK && !state.offset);
 pn_book_id_t first,last;assert(pn_identity_bytes(bytes,PN_UPLOAD_CHUNK,&first)==PN_OK && pn_identity_bytes(bytes+PN_UPLOAD_CHUNK,3,&last)==PN_OK);pn_book_id_t bad=first;bad.sha256[0]^=1;uint64_t ack=999;
 assert(pn_upload_chunk(&upload,0,bytes,PN_UPLOAD_CHUNK,&bad,&ack)==PN_CORRUPT && ack==999 && d->size==0);
 assert(pn_upload_chunk(&upload,1,bytes,PN_UPLOAD_CHUNK,&first,&ack)==PN_BUSY && ack==999);
 assert(pn_upload_chunk(&upload,0,bytes,PN_UPLOAD_CHUNK,&first,&ack)==PN_OK && ack==PN_UPLOAD_CHUNK);
 assert(pn_upload_chunk(&upload,0,bytes,PN_UPLOAD_CHUNK,&first,&ack)==PN_OK && ack==PN_UPLOAD_CHUNK);
 assert(pn_upload_close(&upload)==PN_OK && !pool.used && !pool.live);d->data[d->size++]=99;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && d->size==PN_UPLOAD_CHUNK);assert(pn_upload_close(&upload)==PN_OK);*base=*d;
 size_t frame_size=144+strlen(request.name)+24;
 for(size_t cut=0;cut<=frame_size;cut++){*d=*base;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK);d->cut=true;d->cut_at=cut;ack=999;pn_status_t status=pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack);assert(status==PN_IO);assert(ack==999);assert(pn_upload_state(&upload,&state)==PN_BUSY && pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack)==PN_BUSY && ack==999);assert(pn_upload_close(&upload)==PN_OK);d->cut=false;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_state(&upload,&state)==PN_OK && state.offset==(cut==frame_size?request.size:PN_UPLOAD_CHUNK));assert(pn_upload_close(&upload)==PN_OK && !pool.used && !pool.live);}
 *d=*base;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack)==PN_OK);
 d->bad_format=true;assert(pn_upload_complete(&upload,&request.digest)==PN_UNSUPPORTED && !d->installs);d->bad_format=false;bad=request.digest;bad.sha256[0]^=1;assert(pn_upload_complete(&upload,&bad)==PN_CORRUPT && !d->installs);assert(pn_upload_complete(&upload,&request.digest)==PN_OK && d->installs==1);assert(pn_upload_complete(&upload,&request.digest)==PN_OK && d->installs==1);assert(pn_upload_close(&upload)==PN_OK && pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_state(&upload,&state)==PN_OK && state.phase==PN_UPLOAD_COMMITTED);assert(pn_upload_close(&upload)==PN_OK);
 *d=*base;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack)==PN_OK);d->fail_install=true;assert(pn_upload_complete(&upload,&request.digest)==PN_IO && pn_upload_state(&upload,&state)==PN_OK && state.phase==PN_UPLOAD_VERIFIED);assert(pn_upload_cancel(&upload)==PN_BUSY && pn_upload_close(&upload)==PN_OK);d->fail_install=false;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK);d->cut_commit=true;assert(pn_upload_complete(&upload,&request.digest)==PN_IO && d->installs==1 && !d->part);assert(pn_upload_close(&upload)==PN_OK);d->cut_commit=d->cut=false;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_complete(&upload,&request.digest)==PN_OK && d->installs==1 && pn_upload_close(&upload)==PN_OK);
 // 已确认早期块损坏不能被最后块校验漏过；完成时校验全文。/ Complete checks the whole file, including corruption outside the last acknowledged chunk.
 *d=*base;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack)==PN_OK);d->data[0]^=1;assert(pn_upload_complete(&upload,&request.digest)==PN_CORRUPT && !d->installs && pn_upload_close(&upload)==PN_OK);
 // 未知manifest保持原字节，不能以创建新会话覆盖。/ Preserve unknown manifest bytes; beginning again cannot overwrite them.
 *d=*base;pn_journal_io_t raw={d,read_slot,write_slot};uint8_t payload[1024];size_t payload_size;assert(pn_blob_load(&raw,&pool,payload,sizeof payload,&payload_size)==PN_OK);payload[4]=2;assert(pn_blob_save(&raw,&pool,payload,payload_size)==PN_OK);disk_t unknown=*d;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_UNSUPPORTED && pn_upload_begin(&upload,&pool,&media,&port,&request)==PN_UNSUPPORTED && !memcmp(d,&unknown,sizeof *d));
 // 恢复路径每个观察到的分配失败都释放独占租约。/ Every observed resume allocation failure releases the exclusive lease.
 *d=*base;size_t attempt_start=pool.attempts;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK);size_t requests=pool.attempts-attempt_start;assert(pn_upload_close(&upload)==PN_OK);for(size_t fail=1;fail<=requests;fail++){*d=*base;pool.fail_at=pool.attempts+fail;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_NO_MEMORY && !upload.impl && !pool.used && !pn_media_active(&media));pool.fail_at=0;}
 *d=*base;d->data[0]^=1;assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_CORRUPT && !upload.impl && !pool.used);
 *d=*base;assert(pn_media_detach(&media)==PN_OK && pn_media_attach(&media,999)==PN_OK);assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_STALE_MEDIA && !upload.impl);assert(pn_media_detach(&media)==PN_OK && pn_media_attach(&media,123)==PN_OK);
 assert(pn_upload_resume(&upload,&pool,&media,&port,request.id)==PN_OK && pn_upload_cancel(&upload)==PN_OK && !d->part && pn_upload_chunk(&upload,PN_UPLOAD_CHUNK,bytes+PN_UPLOAD_CHUNK,3,&last,&ack)==PN_CANCELLED);assert(pn_upload_close(&upload)==PN_OK);
 const char *invalid[]={"../a.txt","a/b.txt","a\\b.txt",".a.txt","a.txt ","a.exe","CON.txt","a:bad.txt","a\xc0\xaf.txt"};for(size_t i=0;i<sizeof invalid/sizeof *invalid;i++){strcpy(request.name,invalid[i]);assert(pn_upload_request_validate(&request)!=PN_OK);}strcpy(request.name,"A.TXT");assert(pn_upload_request_validate(&request)==PN_OK);request.kind=PN_UPLOAD_FONT;assert(pn_upload_request_validate(&request)==PN_UNSUPPORTED);
 free(bytes);free(base);free(d);assert(!pool.used && !pool.live && !pn_media_active(&media));puts("upload: durable chunks, every manifest byte cut, restart reconciliation, format gate, exclusive media and cancellation passed");return 0;
}
