set(PN_JPEG_SOURCES
    ${PN_JPEG_ROOT}/vendor/src/jdapimin.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdapistd-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdapistd-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdapistd-16.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdcoefct-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdcoefct-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdcolor-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdcolor-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdcolor-16.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jddctmgr-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jddctmgr-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jddiffct-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jddiffct-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jddiffct-16.c
    ${PN_JPEG_ROOT}/vendor/src/jdhuff.c
    ${PN_JPEG_ROOT}/vendor/src/jdicc.c
    ${PN_JPEG_ROOT}/vendor/src/jdinput.c
    ${PN_JPEG_ROOT}/vendor/src/jdlhuff.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdlossls-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdlossls-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdlossls-16.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdmainct-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdmainct-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdmainct-16.c
    ${PN_JPEG_ROOT}/vendor/src/jdmarker.c
    ${PN_JPEG_ROOT}/vendor/src/jdmaster.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdmerge-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdmerge-12.c
    ${PN_JPEG_ROOT}/vendor/src/jdphuff.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdpostct-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdpostct-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdpostct-16.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdsample-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdsample-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jdsample-16.c
    ${PN_JPEG_ROOT}/vendor/src/jdtrans.c
    ${PN_JPEG_ROOT}/vendor/src/jerror.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctflt-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctflt-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctfst-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctfst-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctint-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctint-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctred-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jidctred-12.c
    ${PN_JPEG_ROOT}/vendor/src/jmemmgr.c
    ${PN_JPEG_ROOT}/vendor/src/jpeg_nbits.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jquant1-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jquant1-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jquant2-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jquant2-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jutils-8.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jutils-12.c
    ${PN_JPEG_ROOT}/vendor/src/wrapper/jutils-16.c
    ${PN_JPEG_ROOT}/vendor/src/jcomapi.c
)
