/*
 * SPDX-License-Identifier: Apache-2.0
 * 中文：PC HTTP适配的单owner原生上传进程，有界命令/数据管道。
 * English: single-owner native upload process for PC HTTP adapters, with bounded command/data pipes.
 * 冻结：不接受客户端根路径，文件事务不由HTTP语言替代。
 * Frozen: no client-supplied root paths; HTTP languages never replace file transactions.
 */
#define _POSIX_C_SOURCE 200809L
#include "pn_upload_files.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
typedef struct {pn_pool_t pool;pn_media_t media;pn_upload_t upload;pn_upload_files_t files;pn_upload_port_t port;const char *root;uint8_t *buffer;} host_t;
static bool decode(const char *hex,uint8_t *out,size_t n){if(strlen(hex)!=2*n)return false;for(size_t i=0;i<n;i++){unsigned byte=0;for(unsigned j=0;j<2;j++){char c=hex[i*2+j];unsigned v=c>='0' && c<='9'?(unsigned)(c-'0'):c>='a' && c<='f'?(unsigned)(c-'a'+10):c>='A' && c<='F'?(unsigned)(c-'A'+10):16;if(v>15)return false;byte=byte*16+v;}out[i]=(uint8_t)byte;}return true;}
static void hex_print(const uint8_t *bytes,size_t n){for(size_t i=0;i<n;i++)printf("%02x",bytes[i]);}
static pn_status_t close_current(host_t *h){pn_status_t status=pn_upload_close(&h->upload);if(status==PN_OK)status=pn_upload_files_close(&h->files);return status;}
static pn_status_t create_port(host_t *h,bool replace,uint64_t old_size,const pn_book_id_t *old){pn_upload_files_options_t options={.root=h->root,.replace=replace,.old_size=old_size};if(old)options.old_digest=*old;return pn_upload_files_open(&h->files,&h->pool,&options,&h->port);}
static pn_status_t ensure(host_t *h,const uint8_t *id,bool force){pn_upload_request_t info;if(!force && h->upload.impl && pn_upload_info(&h->upload,&info)==PN_OK && !memcmp(info.id,id,16))return PN_OK;pn_status_t status=close_current(h);if(status==PN_OK)status=create_port(h,false,0,NULL);if(status==PN_OK)status=pn_upload_resume(&h->upload,&h->pool,&h->media,&h->port,id);if(status!=PN_OK)(void)close_current(h);return status;}
static void emit(host_t *h,pn_status_t code){pn_upload_state_t state={0};pn_upload_request_t info={0};bool available=h->upload.impl && pn_upload_state(&h->upload,&state)==PN_OK && pn_upload_info(&h->upload,&info)==PN_OK;printf("{\"code\":%d",code);if(code==PN_OK && available){printf(",\"offset\":%llu,\"size\":%llu,\"phase\":%u,\"kind\":%u,\"name_hex\":\"",(unsigned long long)state.offset,(unsigned long long)state.size,(unsigned)state.phase,(unsigned)info.kind);hex_print((const uint8_t *)info.name,strlen(info.name));printf("\",\"sha256\":\"");hex_print(info.digest.sha256,32);printf("\",\"id\":\"");hex_print(info.id,16);printf("\"");bool pending=false;if(pn_upload_files_cleanup_pending(&h->files,&pending)==PN_OK)printf(",\"cleanup_pending\":%s",pending?"true":"false");}puts("}");fflush(stdout);}
static pn_status_t metadata(host_t *h,unsigned kind,const char *name){pn_status_t status=close_current(h);if(status!=PN_OK)return status;pn_upload_request_t request={.kind=(pn_upload_kind_t)kind,.size=1};request.id[0]=1;if(strlen(name)>=sizeof request.name)return PN_INVALID;strcpy(request.name,name);status=pn_upload_request_validate(&request);if(status!=PN_OK)return status;const char *folder=kind==1?"books":kind==2?"fonts":kind==3?"covers":"wallpapers";char directory[384],path[384];int n=snprintf(directory,sizeof directory,"%s/%s",h->root,folder);if(n<0 || (size_t)n>=sizeof directory)return PN_LIMIT;struct stat info;if(lstat(directory,&info))return PN_EMPTY;if(!S_ISDIR(info.st_mode))return PN_INVALID;n=snprintf(path,sizeof path,"%s/%s",directory,name);if(n<0 || (size_t)n>=sizeof path)return PN_LIMIT;if(lstat(path,&info))return PN_EMPTY;if(!S_ISREG(info.st_mode) || info.st_size<0)return PN_INVALID;pn_media_lease_t lease;status=pn_media_acquire(&h->media,PN_MEDIA_READ,&lease);pn_book_id_t digest;if(status==PN_OK){status=pn_identity_file(&h->media,&lease,path,512u*1024u*1024u,&digest);(void)pn_media_release(&h->media,&lease);}if(status==PN_OK){printf("{\"code\":0,\"size\":%llu,\"sha256\":\"",(unsigned long long)info.st_size);hex_print(digest.sha256,32);puts("\"}");fflush(stdout);}return status;}
int main(int argc,char **argv){if(argc!=2)return 2;host_t h={.root=argv[1]};if(pn_pool_init(&h.pool,6u*1024u*1024u,NULL,NULL,NULL))return 2;pn_media_init(&h.media);if(pn_media_attach(&h.media,123)!=PN_OK)return 2;h.buffer=pn_alloc(&h.pool,PN_UPLOAD_CHUNK);if(!h.buffer)return 2;pn_status_t started=create_port(&h,false,0,NULL);if(started!=PN_OK){pn_free(h.buffer);return 2;}if(pn_upload_files_close(&h.files)!=PN_OK)return 2;puts("{\"code\":0,\"ready\":true}");fflush(stdout);char line[1100];
 while(fgets(line,sizeof line,stdin)){pn_status_t status=PN_INVALID;char command[12],id_hex[33],digest_hex[65],name_hex[511],old_hex[65];unsigned kind,replace;unsigned long long size,at,old_size;uint8_t id[16];pn_book_id_t digest,old;int consumed=0;
  if(!strchr(line,'\n'))break;
  if(sscanf(line,"%11s",command)!=1){emit(&h,status);continue;}
  if(!strcmp(command,"BEGIN") && sscanf(line,"BEGIN %32s %u %llu %64s %510s %u %llu %64s %n",id_hex,&kind,&size,digest_hex,name_hex,&replace,&old_size,old_hex,&consumed)==8 && !line[consumed]){pn_upload_request_t request={.kind=(pn_upload_kind_t)kind,.size=size,.has_digest=true};size_t length=strlen(name_hex)/2;if(length && length<sizeof request.name && strlen(name_hex)%2==0 && decode(id_hex,request.id,16) && decode(digest_hex,request.digest.sha256,32) && decode(old_hex,old.sha256,32) && decode(name_hex,(uint8_t *)request.name,length) && !memchr(request.name,0,length) && replace<=1){status=close_current(&h);if(status==PN_OK)status=create_port(&h,replace!=0,old_size,&old);if(status==PN_OK)status=pn_upload_begin(&h.upload,&h.pool,&h.media,&h.port,&request);if(status!=PN_OK)(void)close_current(&h);}}
  else if(!strcmp(command,"OPEN") && sscanf(line,"OPEN %32s %n",id_hex,&consumed)==1 && !line[consumed] && decode(id_hex,id,16))status=ensure(&h,id,true);
  else if(!strcmp(command,"CHUNK") && sscanf(line,"CHUNK %32s %llu %llu %64s %n",id_hex,&at,&size,digest_hex,&consumed)==4 && !line[consumed]){if(!size || size>PN_UPLOAD_CHUNK)break;if(fread(h.buffer,1,(size_t)size,stdin)!=(size_t)size)break;if(decode(id_hex,id,16) && decode(digest_hex,digest.sha256,32)){status=ensure(&h,id,false);uint64_t ack;if(status==PN_OK)status=pn_upload_chunk(&h.upload,at,h.buffer,(size_t)size,&digest,&ack);}}
  else if(!strcmp(command,"END") && sscanf(line,"END %32s %64s %n",id_hex,digest_hex,&consumed)==2 && !line[consumed] && decode(id_hex,id,16) && decode(digest_hex,digest.sha256,32)){status=ensure(&h,id,false);if(status==PN_OK)status=pn_upload_complete(&h.upload,&digest);}
  else if(!strcmp(command,"CANCEL") && sscanf(line,"CANCEL %32s %n",id_hex,&consumed)==1 && !line[consumed] && decode(id_hex,id,16)){status=ensure(&h,id,false);if(status==PN_OK)status=pn_upload_cancel(&h.upload);}
  else if(!strcmp(command,"FILE") && sscanf(line,"FILE %u %510s %n",&kind,name_hex,&consumed)==2 && !line[consumed]){size_t length=strlen(name_hex)/2;char name[256]={0};if(length && length<sizeof name && strlen(name_hex)%2==0 && decode(name_hex,(uint8_t *)name,length) && !memchr(name,0,length)){status=metadata(&h,kind,name);if(status==PN_OK)continue;}}
  else if(!strcmp(command,"EXIT")){status=close_current(&h);emit(&h,status);break;}
  emit(&h,status);
 }
 pn_status_t closed=close_current(&h);pn_free(h.buffer);return closed==PN_OK && !h.pool.used && !h.pool.live && !pn_media_active(&h.media)?0:1;
}
