if(ESP_PLATFORM)
    idf_component_register(SRCS vendor/spng/spng.c INCLUDE_DIRS vendor/spng REQUIRES pn_zlib)
    set(spng_target ${COMPONENT_LIB})
else()
    add_library(pn_spng STATIC vendor/spng/spng.c)
    set(spng_target pn_spng)
    target_include_directories(${spng_target} PUBLIC vendor/spng)
    target_link_libraries(${spng_target} PUBLIC pn_zlib m)
    if(PN_SANITIZERS)
        target_compile_options(${spng_target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
        target_link_options(${spng_target} PUBLIC -fsanitize=address,undefined)
    endif()
endif()
target_compile_definitions(${spng_target} PUBLIC SPNG_STATIC PRIVATE SPNG_DISABLE_OPT)
target_compile_options(${spng_target} PRIVATE -include ${CMAKE_CURRENT_SOURCE_DIR}/config/pn_spng_read_only.h)
