if(ESP_PLATFORM)
 idf_component_register(SRCS "vendor/cJSON.c" INCLUDE_DIRS "vendor")
 target_compile_definitions(${COMPONENT_LIB} PRIVATE CJSON_NESTING_LIMIT=16)
else()
 add_library(pn_cjson STATIC vendor/cJSON.c)
 target_include_directories(pn_cjson PUBLIC vendor)
 target_compile_definitions(pn_cjson PRIVATE CJSON_NESTING_LIMIT=16)
 if(PN_SANITIZERS)
  target_compile_options(pn_cjson PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_link_options(pn_cjson PUBLIC -fsanitize=address,undefined)
 endif()
endif()
