idf_component_register(SRCS "pn_media.c" "pn_journal.c" "pn_blob.c" "pn_recent.c" "pn_network_store.c" "pn_input_prefs.c" "pn_identity.c" "pn_progress.c" "pn_epub_progress.c" "pn_epub_save.c" "pn_style.c" "pn_font_preferences.c" "pn_save_policy.c" "pn_bookmark.c" "pn_bookmarks.c" "pn_epub_bookmarks.c" INCLUDE_DIRS "include" REQUIRES pn_core)
