"""生成GB2312一级汉字拼音首字母表，不手改产物。 / Generate pinyin initials for GB2312 level-1 hanzi; never hand-edit output.

GB2312一级汉字（B0A1–D7F9）按拼音排序，首字母边界为通行常量；二级汉字按部首排列，不收录。
GB2312 level-1 hanzi (B0A1–D7F9) are ordered by pinyin with well-known initial boundaries; level-2 hanzi follow radicals and are excluded.
多音字只取GB2312排序位置对应的读音，仅用于书名排序与跳转。
Polyphones take the reading implied by their GB2312 position, used only for title ordering and jumps.
"""
import argparse
import pathlib
import sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "components/pn_library/pn_pinyin.generated.h"
BOUNDS = [(0xB0A1, "a"), (0xB0C5, "b"), (0xB2C1, "c"), (0xB4EE, "d"), (0xB6EA, "e"), (0xB7A2, "f"), (0xB8C1, "g"), (0xB9FE, "h"),
          (0xBBF7, "j"), (0xBFA6, "k"), (0xC0AC, "l"), (0xC2E8, "m"), (0xC4C3, "n"), (0xC5B6, "o"), (0xC5BE, "p"), (0xC6DA, "q"),
          (0xC8BB, "r"), (0xC8F6, "s"), (0xCBFA, "t"), (0xCDDA, "w"), (0xCEF4, "x"), (0xD1B9, "y"), (0xD4D1, "z")]
END = 0xD7F9
def letter(code):
    result = None
    for start, value in BOUNDS:
        if code >= start:
            result = value
    return result
def generate():
    pairs = []
    for lead in range(0xB0, 0xD8):
        for trail in range(0xA1, 0xFF):
            code = (lead << 8) | trail
            if code > END:
                continue
            char = bytes([lead, trail]).decode("gb2312", errors="strict")
            pairs.append((ord(char), letter(code)))
    pairs.sort()
    if len(pairs) != 3755 or len({p[0] for p in pairs}) != 3755:
        raise SystemExit("unexpected GB2312 level-1 set")
    lines = ["/*", " * SPDX-FileCopyrightText: 2026 pico_nano contributors", " * SPDX-License-Identifier: Apache-2.0",
             " * 自动生成：tools/gen_pinyin.py使用Python严格gb2312 codec与一级汉字拼音边界。/ Generated by tools/gen_pinyin.py from the strict gb2312 codec and level-1 pinyin bounds.",
             " * 勿手改；按Unicode升序，供二分查找。/ Do not hand-edit; sorted by Unicode for binary search.", " */", "#pragma once", "#include <stdint.h>",
             f"#define PN_PINYIN_COUNT {len(pairs)}",
             "static const uint16_t pn_pinyin_code[PN_PINYIN_COUNT] = {"]
    for offset in range(0, len(pairs), 16):
        lines.append("    " + ",".join(f"0x{code:04x}" for code, _ in pairs[offset:offset+16]) + ",")
    lines.append("};")
    lines.append("static const char pn_pinyin_letter[PN_PINYIN_COUNT + 1] =")
    text = "".join(value for _, value in pairs)
    for offset in range(0, len(text), 96):
        lines.append('    "' + text[offset:offset+96] + '"')
    lines[-1] += ";"
    return "\n".join(lines + [""])
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf8") != text:
            print("pinyin generated table differs", file=sys.stderr)
            return 1
        print("pinyin generated table matches")
        return 0
    OUTPUT.write_text(text, encoding="utf8", newline="\n")
    return 0
if __name__ == "__main__":
    sys.exit(main())
