"""生成GBK到Unicode数据表，不手改产物。 / Generate GBK-to-Unicode data; never hand-edit output."""
import argparse
import pathlib
import sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "components/pn_text/pn_gbk.generated.h"
def generate():
    values = []
    for lead in range(0x81, 0xff):
        for trail in range(0x40, 0xff):
            try:
                value = ord(bytes([lead, trail]).decode("gbk", errors="strict")) if trail != 0x7f else 0
            except UnicodeDecodeError:
                value = 0
            values.append(value)
    lines = ["/*", " * SPDX-FileCopyrightText: 2026 pico_nano contributors", " * SPDX-License-Identifier: Apache-2.0",
             " * 自动生成：tools/gen_gbk.py使用Python严格gbk codec。/ Generated by tools/gen_gbk.py using Python strict gbk codec.",
             " * 勿手改；未定义编码为0。/ Do not hand-edit; undefined encodings are zero.", " */", "#pragma once", "#include <stdint.h>",
             "static const uint16_t pn_gbk_table[126 * 191] = {"]
    for offset in range(0, len(values), 16):
        lines.append("    " + ",".join(f"0x{value:04x}" for value in values[offset:offset+16]) + ",")
    return "\n".join(lines + ["};", ""])
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf8") != text:
            print("GBK generated table differs", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(text, encoding="utf8", newline="\n")
    print("GBK table: 24066 slots, " + ("verified" if args.check else "generated"))
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
